Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: <<-SHELL
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
      systemctl reload sshd
      echo -e "admin\nadmin" | passwd root > /dev/null 2>&1
    SHELL
  
    (1..1).each do |i|
      config.vm.define "c1-master#{i}" do | node |
        node.vm.box = "bento/ubuntu-20.04"
        node.vm.hostname = "cp1-master#{i}"
        node.vm.network "private_network", ip: "172.16.14.20#{i}"
        node.vm.provider "virtualbox" do | vb |
          vb.name = "cp1-master#{i}"
          vb.memory = 2024
          vb.cpus = 1
        end
      end
    end
  end